#!/usr/bin/env python3
"""Run a skill command inside a v1.8 app-ready run bundle."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

from _internal.public_contract import build_blocked_payload, build_tool_payload
from _internal.provenance_utils import sanitize_payload
from _internal.run_bundle import (
    ensure_run_bundle,
    finalize_existing_run_bundle,
    load_child_manifest,
    load_summary,
    write_command_txt,
    write_run_manifest,
)


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-dir", required=True, help="Destination run bundle directory.")
    parser.add_argument("--tool", default="app_run_bundle", help="Logical tool name if the child does not emit a summary.")
    parser.add_argument("command", nargs=argparse.REMAINDER, help="Child command after --.")
    args = parser.parse_args()
    if args.command and args.command[0] == "--":
        args.command = args.command[1:]
    if not args.command:
        parser.error("A child command is required after --.")
    return args


def fallback_payload(tool: str, command: list[str], returncode: int, stderr: str, stdout: str, summary_missing: bool) -> dict:
    status = "ok" if returncode == 0 and not summary_missing else "fail"
    finding = "Child command did not write run/summary.json." if summary_missing else (stderr or stdout or "Child command failed.")
    return build_tool_payload(
        tool,
        status=status,
        notes=["Generated by app_run_bundle.py because the child command did not provide a complete v1.8 summary."],
        artifacts={},
        results={
            "command": command,
            "returncode": returncode,
            "summary_missing": summary_missing,
            "stderr_tail": stderr[-2000:],
            "stdout_tail": stdout[-2000:],
        },
        qa={
            "status": status,
            "findings": [] if status == "ok" else [finding],
            "metrics": {"returncode": returncode},
        },
    )


def main() -> int:
    args = parse_args()
    run_dir = Path(args.run_dir).expanduser()
    if run_dir.is_symlink() or (run_dir.exists() and (not run_dir.is_dir() or any(run_dir.iterdir()))):
        finding = (
            "--run-dir must be absent or empty; refusing to overwrite or reinterpret a "
            "pre-existing run bundle."
        )
        payload = build_blocked_payload(
            "app_run_bundle",
            finding,
            artifacts={},
            results={"blocked_run_dir": str(run_dir)},
        )
        print(json.dumps(sanitize_payload(payload), indent=2, ensure_ascii=True))
        return 2
    layout = ensure_run_bundle(args.run_dir)
    write_command_txt(layout, args.command, Path.cwd())
    completed = subprocess.run(args.command, text=True, capture_output=True, check=False)
    layout.stdout_txt.write_text(completed.stdout or "", encoding="utf-8")
    layout.stderr_txt.write_text(completed.stderr or "", encoding="utf-8")
    child_manifest = load_child_manifest(layout)
    payload = load_summary(layout)
    if payload is None:
        payload = fallback_payload(
            args.tool,
            args.command,
            completed.returncode,
            completed.stderr or "",
            completed.stdout or "",
            summary_missing=True,
        )
    payload.setdefault("tool", args.tool)
    payload.setdefault("command", {"argv": args.command, "cwd": str(Path.cwd()), "redacted": False})
    payload["command"] = {
        "argv": [str(item) for item in args.command],
        "cwd": str(Path.cwd()),
        "redacted": False,
    }
    payload["returncode"] = completed.returncode
    enriched = finalize_existing_run_bundle(layout, payload, returncode=completed.returncode)
    write_run_manifest(
        layout,
        payload=enriched,
        command=args.command,
        returncode=completed.returncode,
        child_manifest=child_manifest,
    )
    # Re-finalize after the run-level manifest exists so typed_artifacts can mark it as present.
    enriched = finalize_existing_run_bundle(layout, enriched, returncode=completed.returncode)
    print(json.dumps(sanitize_payload(enriched), indent=2, ensure_ascii=True))
    return completed.returncode


if __name__ == "__main__":
    raise SystemExit(main())
