#!/usr/bin/env python3
"""Scaffold and populate a Spanish report for legacy spectroscopy coursework."""

from __future__ import annotations

import argparse
import csv
import json
import shutil
import sys
import unicodedata
from pathlib import Path

from _internal.provenance_utils import public_path, standard_qa_payload, standard_tool_payload, write_manifest
from _internal.runtime_common import configure_runtime


SCAFFOLD_TOOL = "legacy_spectroscopy_report_builder.scaffold"

SECTION_FILES = [
    ("01_objetivo_materiales.tex", "Objetivo y materiales"),
    ("02_entorno_trazabilidad.tex", "Entorno legacy y trazabilidad"),
    ("03_inventario_multispec.tex", "Inventario MULTISPE"),
    ("04_velocidad_radial.tex", "Velocidad radial"),
    ("05_vsini.tex", "v sin i"),
    ("06_istarmod.tex", "Sustraccion espectral con iSTARMOD"),
    ("07_anchuras_equivalentes.tex", "Anchuras equivalentes"),
    ("08_discusion.tex", "Discusion, limitaciones y comparacion con literatura"),
    ("09_apendices.tex", "Apendices"),
]


class InputValidationError(Exception):
    """Raised when scaffold paths are unsafe to write."""

    def __init__(self, issues: list[dict]):
        super().__init__("; ".join(item["detail"] for item in issues))
        self.issues = issues


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)

    scaffold = subparsers.add_parser("scaffold", help="Create a narrow Spanish LaTeX report project.")
    scaffold.add_argument("output_dir")
    scaffold.add_argument("--title", default="Practica de espectroscopia legacy")
    scaffold.add_argument("--author", default="Nombre del estudiante")
    scaffold.add_argument("--summary-json")
    scaffold.add_argument("--manifest-json")

    populate = subparsers.add_parser("populate", help="Populate the report project from real workflow outputs.")
    populate.add_argument("project_dir")
    populate.add_argument("--envcheck")
    populate.add_argument("--inventory-summary")
    populate.add_argument("--fxcor-summary", action="append", default=[])
    populate.add_argument("--rv-summary")
    populate.add_argument("--istarmod-summary")
    populate.add_argument("--li-summary", action="append", default=[], help="Optional Li I 6707.8 / EW summary JSON generated by li6708_equivalent_width_workbench.py.")
    populate.add_argument("--external-reference-summary", help="Optional JSON from legacy_external_reference_check.py.")
    populate.add_argument("--summary-json")
    populate.add_argument("--manifest-json")
    return parser.parse_args()


def tex_escape(value: str) -> str:
    replacements = {
        "\\": r"\textbackslash{}",
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }
    text = unicodedata.normalize("NFC", str(value))
    for source, target in replacements.items():
        text = text.replace(source, target)
    return text


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text.strip() + "\n", encoding="utf-8")


def scaffold_owned_files(project_dir: Path) -> list[Path]:
    return [project_dir / "main.tex"] + [project_dir / "sections" / filename for filename, _ in SECTION_FILES]


def scaffold_reserved_paths(project_dir: Path) -> set[Path]:
    return {
        project_dir,
        project_dir / "sections",
        project_dir / "figures",
        project_dir / "tables",
        *scaffold_owned_files(project_dir),
    }


def first_non_directory_ancestor(path: Path) -> Path | None:
    for parent in (path.parent, *path.parent.parents):
        if parent.exists():
            return parent if not parent.is_dir() else None
    return None


def validate_auxiliary_output_path(raw_path: str | None, label: str, reserved_paths: set[Path]) -> list[dict]:
    if not raw_path:
        return []
    path = Path(raw_path).expanduser().resolve(strict=False)
    issues = []
    if path in reserved_paths:
        issues.append(
            {
                "severity": "high",
                "title": "Auxiliary output would overwrite scaffold content",
                "detail": f"{label} points to a scaffold-owned path: {public_path(path)}",
                "path": public_path(path),
                "argument": label,
            }
        )
    if path.exists() and path.is_dir():
        issues.append(
            {
                "severity": "high",
                "title": "Auxiliary output path is a directory",
                "detail": f"{label} must point to a file, not a directory: {public_path(path)}",
                "path": public_path(path),
                "argument": label,
            }
        )
    blocked_parent = first_non_directory_ancestor(path)
    if blocked_parent is not None:
        issues.append(
            {
                "severity": "high",
                "title": "Auxiliary output parent is not a directory",
                "detail": f"{label} cannot be written because an ancestor is a file: {public_path(blocked_parent)}",
                "path": public_path(path),
                "argument": label,
            }
        )
    return issues


def validate_scaffold_request(project_dir: Path, args) -> list[dict]:
    issues = []
    if project_dir.exists() and not project_dir.is_dir():
        issues.append(
            {
                "severity": "high",
                "title": "Output path is not a directory",
                "detail": f"output_dir already exists and is not a directory: {public_path(project_dir)}",
                "path": public_path(project_dir),
                "argument": "output_dir",
            }
        )
    for path in scaffold_owned_files(project_dir):
        if path.exists():
            issues.append(
                {
                    "severity": "high",
                    "title": "Existing scaffold file would be overwritten",
                    "detail": f"Refusing to overwrite existing scaffold file: {public_path(path)}",
                    "path": public_path(path),
                    "argument": "output_dir",
                }
            )
    reserved = scaffold_reserved_paths(project_dir)
    issues.extend(validate_auxiliary_output_path(args.summary_json, "--summary-json", reserved))
    issues.extend(validate_auxiliary_output_path(args.manifest_json, "--manifest-json", reserved))
    if args.summary_json and args.manifest_json:
        summary_path = Path(args.summary_json).expanduser().resolve(strict=False)
        manifest_path = Path(args.manifest_json).expanduser().resolve(strict=False)
        if summary_path == manifest_path:
            issues.append(
                {
                    "severity": "high",
                    "title": "Auxiliary output paths collide",
                    "detail": f"--summary-json and --manifest-json point to the same file: {public_path(summary_path)}",
                    "path": public_path(summary_path),
                    "argument": "--summary-json/--manifest-json",
                }
            )
    return issues


def scaffold_payload(project_dir: Path, *, status: str, notes: list[str], artifacts: dict, results: dict, findings: list[dict] | None = None) -> dict:
    return standard_tool_payload(
        SCAFFOLD_TOOL,
        status=status,
        notes=notes,
        artifacts=artifacts,
        results=results,
        qa=standard_qa_payload(
            status=status,
            findings=findings or [],
            metrics={
                "section_count": len(SECTION_FILES),
                "finding_count": len(findings or []),
                "created_file_count": len(scaffold_owned_files(project_dir)) if status == "ok" else 0,
            },
        ),
    )


def emit_scaffold_payload(payload: dict, args, *, skip_summary_json: bool = False) -> None:
    rendered = json.dumps(payload, indent=2, ensure_ascii=True)
    print(rendered)
    if args.summary_json and not skip_summary_json:
        summary_path = Path(args.summary_json).expanduser().resolve(strict=False)
        summary_path.parent.mkdir(parents=True, exist_ok=True)
        summary_path.write_text(rendered + "\n", encoding="utf-8")


def scaffold_main_tex(project_dir: Path, title: str, author: str) -> None:
    main_tex = rf"""
\documentclass[a4paper,11pt]{{article}}
\usepackage[utf8]{{inputenc}}
\usepackage[T1]{{fontenc}}
\usepackage[spanish, es-nodecimaldot]{{babel}}
\usepackage{{graphicx}}
\usepackage{{booktabs}}
\usepackage{{longtable}}
\usepackage{{siunitx}}
\usepackage{{hyperref}}
\usepackage{{geometry}}
\geometry{{margin=2.5cm}}

\title{{{tex_escape(title)}}}
\author{{{tex_escape(author)}}}
\date{{\today}}

\begin{{document}}
\maketitle

\begin{{abstract}}
Este proyecto se ha generado como memoria de trabajo para una práctica de espectroscopia legacy en macOS. Sustituye este resumen por una síntesis breve de la pregunta física, los materiales reales usados y la conclusión más defendible.
\end{{abstract}}

\tableofcontents
\newpage

\section{{Objetivo y materiales}}
\input{{sections/01_objetivo_materiales}}

\section{{Entorno legacy y trazabilidad}}
\input{{sections/02_entorno_trazabilidad}}

\section{{Inventario MULTISPE}}
\input{{sections/03_inventario_multispec}}

\section{{Velocidad radial}}
\input{{sections/04_velocidad_radial}}

\section{{v sin i}}
\input{{sections/05_vsini}}

\section{{Sustracción espectral con iSTARMOD}}
\input{{sections/06_istarmod}}

\section{{Anchuras equivalentes}}
\input{{sections/07_anchuras_equivalentes}}

\section{{Discusión, limitaciones y comparación con literatura}}
\input{{sections/08_discusion}}

\appendix
\section{{Apéndices}}
\input{{sections/09_apendices}}

\end{{document}}
"""
    write_text(project_dir / "main.tex", main_tex)


def scaffold_sections(project_dir: Path) -> None:
    placeholders = {
        "01_objetivo_materiales.tex": "Describe aqui el objetivo cientifico de la practica, el material suministrado (PDFs, FITS, calibraciones, iSTARMOD) y la lista de entregables esperados.",
        "02_entorno_trazabilidad.tex": "Resume aqui el entorno legacy usado, las comprobaciones previas, la ruta de trabajo no destructiva y cualquier riesgo residual de compatibilidad.",
        "03_inventario_multispec.tex": "Sustituye este texto con un inventario por fichero y por orden de los espectros MULTISPE realmente usados.",
        "04_velocidad_radial.tex": "Resume aqui la ruta de fxcor, los ordenes retenidos y la velocidad radial final con sus caveats.",
        "05_vsini.tex": "Describe aqui la primera pasada de v sin i basada en la anchura de la CCF y la calibracion externa.",
        "06_istarmod.tex": "Documenta aqui la copia limpia de iSTARMOD, el .sm utilizado, la linea estudiada y los outputs generados.",
        "07_anchuras_equivalentes.tex": "Añade aqui las anchuras equivalentes y como se interpretan dentro del alcance real de la practica.",
        "08_discusion.tex": "Redacta aqui que resultados son robustos, cuales son solo indicativos y como se comparan con literatura o valores esperados.",
        "09_apendices.tex": "Usa este apendice para tablas largas, logs relevantes, comandos reproducibles y notas metodologicas.",
    }
    for filename, _ in SECTION_FILES:
        write_text(project_dir / "sections" / filename, placeholders[filename])


def cmd_scaffold(args):
    configure_runtime("legacy_spectroscopy_report_builder_scaffold")
    project_dir = Path(args.output_dir).expanduser().resolve()
    validation_issues = validate_scaffold_request(project_dir, args)
    if validation_issues:
        raise InputValidationError(validation_issues)
    (project_dir / "sections").mkdir(parents=True, exist_ok=True)
    (project_dir / "figures").mkdir(parents=True, exist_ok=True)
    (project_dir / "tables").mkdir(parents=True, exist_ok=True)
    scaffold_main_tex(project_dir, args.title, args.author)
    scaffold_sections(project_dir)

    artifacts = {
        "project_dir": str(project_dir),
        "main_tex": str(project_dir / "main.tex"),
        "sections_dir": str(project_dir / "sections"),
        "figures_dir": str(project_dir / "figures"),
        "tables_dir": str(project_dir / "tables"),
        "summary_json": str(Path(args.summary_json).expanduser().resolve(strict=False)) if args.summary_json else None,
        "manifest_json": str(Path(args.manifest_json).expanduser().resolve(strict=False)) if args.manifest_json else None,
    }
    payload = scaffold_payload(
        project_dir,
        status="ok",
        notes=["Proyecto LaTeX estrecho creado en espanol para la practica legacy de espectroscopia."],
        artifacts=artifacts,
        results={
            "output_dir": str(project_dir),
            "section_count": len(SECTION_FILES),
            "created_files": [str(path) for path in scaffold_owned_files(project_dir)],
        },
    )
    emit_scaffold_payload(payload, args)
    if args.manifest_json:
        write_manifest(
            args.manifest_json,
            inputs=[],
            outputs=[project_dir],
            parameters={"tool": SCAFFOLD_TOOL},
            command=" ".join(sys.argv),
            notes=payload["notes"],
        )
    return 0


def emit_blocked_scaffold(args, error: InputValidationError) -> int:
    project_dir = Path(args.output_dir).expanduser().resolve(strict=False)
    artifacts = {
        "project_dir": str(project_dir),
        "summary_json": str(Path(args.summary_json).expanduser().resolve(strict=False)) if args.summary_json else None,
        "manifest_json": str(Path(args.manifest_json).expanduser().resolve(strict=False)) if args.manifest_json else None,
    }
    payload = scaffold_payload(
        project_dir,
        status="blocked",
        notes=["Scaffold bloqueado para evitar sobrescribir archivos o emitir un resultado enganoso."],
        artifacts=artifacts,
        results={
            "output_dir": str(project_dir),
            "section_count": len(SECTION_FILES),
            "created_files": [],
            "blockers": error.issues,
        },
        findings=error.issues,
    )
    skip_summary = any(item.get("argument") == "--summary-json" for item in error.issues)
    emit_scaffold_payload(payload, args, skip_summary_json=skip_summary)
    return 2


def load_json(path: str | None) -> dict:
    if not path:
        return {}
    candidate = Path(path).expanduser().resolve()
    if not candidate.exists():
        return {}
    return json.loads(candidate.read_text(encoding="utf-8"))


def read_csv_rows(path: str | None) -> list[dict]:
    if not path:
        return []
    candidate = Path(path).expanduser()
    if not candidate.exists():
        return []
    with candidate.open(encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def copy_artifact_if_exists(raw_path: str | None, target_dir: Path) -> str | None:
    if not raw_path:
        return None
    source = Path(raw_path).expanduser()
    if not source.exists() or not source.is_file():
        return None
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / source.name
    shutil.copy2(source, target)
    return target.name


def write_simple_table(path: Path, headers: list[str], rows: list[list[str]]) -> None:
    lines = [
        r"\begin{table}[h]",
        r"\centering",
        r"\small",
        r"\begin{tabular}{" + "l" * len(headers) + "}",
        r"\toprule",
        " & ".join(tex_escape(item) for item in headers) + r" \\",
        r"\midrule",
    ]
    for row in rows:
        lines.append(" & ".join(tex_escape(item) for item in row) + r" \\")
    lines.extend([r"\bottomrule", r"\end{tabular}", r"\end{table}"])
    write_text(path, "\n".join(lines))


def populate_env_section(project_dir: Path, env_payload: dict) -> str:
    if not env_payload:
        return "Pendiente de poblar con legacy_spectroscopy_envcheck.py."
    results = env_payload.get("results", {})
    tools = results.get("legacy_tools", {})
    assets = results.get("detected_practice_assets", {})
    lines = [
        f"Estado general del preflight: \\texttt{{{tex_escape(env_payload.get('status', 'warning'))}}}.",
        "",
        f"Workspace recomendado: \\texttt{{{tex_escape(results.get('recommended_workspace_root', 'pendiente'))}}}.",
        f"Ruta original con riesgo legacy: \\texttt{{{tex_escape(str(results.get('legacy_safe_workspace_needed')))}}}.",
        "",
        "Herramientas detectadas:",
        r"\begin{itemize}",
        rf"\item \texttt{{cl}}: {tex_escape(str(bool(tools.get('cl'))))}",
        rf"\item \texttt{{mkiraf}}: {tex_escape(str(bool(tools.get('mkiraf'))))}",
        rf"\item \texttt{{xgterm}}: {tex_escape(str(bool(tools.get('xgterm'))))}",
        rf"\item \texttt{{pdflatex}}: {tex_escape(str(bool(tools.get('pdflatex'))))}",
        r"\end{itemize}",
        "",
        f"FITS detectados: {tex_escape(str(assets.get('fits_count', 0)))}.",
    ]
    return "\n".join(lines)


def populate_inventory_section(project_dir: Path, inventory_payload: dict) -> tuple[str, list[str]]:
    artifacts = []
    if not inventory_payload:
        return "Pendiente de poblar con \\texttt{echelle\\_multispec\\_inventory.py}.", artifacts
    results = inventory_payload.get("results", {})
    files = results.get("files", [])
    lines = [
        f"Se inventariaron {tex_escape(str(results.get('file_count', len(files))))} fichero(s) y {tex_escape(str(results.get('order_count', 'pendiente')))} orden(es).",
        "",
    ]
    if files:
        preview_rows = []
        for item in files[:6]:
            preview_rows.append([
                item.get("file_name", ""),
                str(item.get("order_count", "")),
                str(item.get("lambda_min_global", "")),
                str(item.get("lambda_max_global", "")),
            ])
        write_simple_table(project_dir / "tables" / "inventario_multispec.tex", ["Fichero", "Ordenes", "lambda min", "lambda max"], preview_rows)
        lines.append(r"\input{tables/inventario_multispec}")
        artifacts.append(str(project_dir / "tables" / "inventario_multispec.tex"))
    else:
        lines.append("No hay una tabla de inventario disponible todavia.")
    return "\n".join(lines), artifacts


def populate_rv_sections(project_dir: Path, fxcor_payloads: list[dict], rv_payload: dict) -> tuple[str, str, list[str]]:
    artifacts = []
    rv_text = ["Pendiente de poblar con \\texttt{fxcor\\_iraf\\_workbench.py} y \\texttt{legacy\\_rv\\_coursework\\_workbench.py}."]
    vsini_text = ["Pendiente de poblar con \\texttt{legacy\\_rv\\_coursework\\_workbench.py}."]
    if fxcor_payloads:
        case_counts = sum(len(item.get("results", {}).get("case_runs", [])) for item in fxcor_payloads)
        rv_text = [f"Se lanzaron {case_counts} caso(s) automáticos de \\texttt{{fxcor}} en copias derivadas.", ""]
    if rv_payload:
        rv_summaries = rv_payload.get("results", {}).get("rv_summaries", [])
        if rv_summaries:
            if not fxcor_payloads:
                rv_text = ["Se incorporaron resúmenes reproducibles de velocidad radial ya calculados.", ""]
            rv_text.append("Resumen de velocidades radiales:")
            rv_text.append(r"\begin{itemize}")
            for item in rv_summaries:
                states = []
                if item.get("measurement_state"):
                    states.append(f"medicion={item['measurement_state']}")
                if item.get("adoption_state"):
                    states.append(f"adopcion={item['adoption_state']}")
                if item.get("physical_robustness"):
                    states.append(f"robustez={item['physical_robustness']}")
                state_text = f" Estado: {', '.join(states)}." if states else ""
                rv_text.append(
                    rf"\item {tex_escape(item['label'])}: {item['vhelio_media_kms']:.4f} $\pm$ {item['vhelio_err_media_kms']:.4f} km/s con {item['n_ordenes']} orden(es).{tex_escape(state_text)}"
                )
            rv_text.append(r"\end{itemize}")
        rv_plot = copy_artifact_if_exists(rv_payload.get("artifacts", {}).get("rv_plot"), project_dir / "figures")
        if rv_plot:
            rv_text.extend(
                [
                    r"\begin{figure}[h]",
                    r"\centering",
                    rf"\includegraphics[width=0.9\linewidth]{{figures/{tex_escape(rv_plot)}}}",
                    r"\caption{Resumen ligero de velocidades radiales por orden.}",
                    r"\end{figure}",
                ]
            )
            artifacts.append(str(project_dir / "figures" / rv_plot))
        vsini_rows = rv_payload.get("results", {}).get("vsini_rows", [])
        if vsini_rows:
            vsini_text = ["Resumen de la primera pasada de $v \\sin i$:", r"\begin{itemize}"]
            for item in vsini_rows:
                flags = item.get("quality_flags") or []
                flag_text = f" Indicadores: {', '.join(flags)}." if flags else ""
                states = []
                if item.get("measurement_state"):
                    states.append(f"medicion={item['measurement_state']}")
                if item.get("adoption_state"):
                    states.append(f"adopcion={item['adoption_state']}")
                if item.get("physical_robustness"):
                    states.append(f"robustez={item['physical_robustness']}")
                state_text = f" Estado: {', '.join(states)}." if states else ""
                vsini_text.append(
                    rf"\item {tex_escape(item['label'])}: FWHM={tex_escape(str(item['fwhm_pix']))} pix, $v \sin i$={tex_escape(str(item['vsini_interp_kms']))} km/s.{tex_escape(flag_text)}{tex_escape(state_text)}"
                )
            vsini_text.append(r"\end{itemize}")
        calibration_plot = copy_artifact_if_exists(rv_payload.get("artifacts", {}).get("calibration_plot"), project_dir / "figures")
        if calibration_plot:
            vsini_text.extend(
                [
                    r"\begin{figure}[h]",
                    r"\centering",
                    rf"\includegraphics[width=0.85\linewidth]{{figures/{tex_escape(calibration_plot)}}}",
                    r"\caption{Calibración FWHM--$v \sin i$ y puntos de la práctica.}",
                    r"\end{figure}",
                ]
            )
            artifacts.append(str(project_dir / "figures" / calibration_plot))
    return "\n".join(rv_text), "\n".join(vsini_text), artifacts


def populate_istarmod_section(project_dir: Path, payload: dict) -> tuple[str, list[str]]:
    artifacts = []
    if not payload:
        return "Pendiente de poblar con \\texttt{istarmod\\_workbench.py}.", artifacts
    results = payload.get("results", {})
    lines = [
        f"Estado de la corrida: \\texttt{{{tex_escape(payload.get('status', 'warning'))}}}.",
        f"Archivo .sm usado: \\texttt{{{tex_escape(results.get('sm_file', 'pendiente'))}}}.",
        "",
        "Esta seccion documenta la validacion tecnica del arbol derivado y no debe confundirse con una interpretacion cientifica cerrada sin revisar el perfil residual y la medida de EW.",
    ]
    for artifact_key in ["log_path"]:
        artifact_name = copy_artifact_if_exists(payload.get("artifacts", {}).get(artifact_key), project_dir / "figures")
        if artifact_name:
            artifacts.append(str(project_dir / "figures" / artifact_name))
    return "\n".join(lines), artifacts


def populate_equivalent_width_section(project_dir: Path, payloads: list[dict]) -> tuple[str, list[str]]:
    artifacts = []
    if not payloads:
        return (
            "Pendiente de poblar con medidas reproducibles de anchura equivalente. "
            "Para Li I 6707.8 en esta ruta puede usarse \\texttt{li6708\\_equivalent\\_width\\_workbench.py}.",
            artifacts,
        )

    lines = ["Medidas de anchura equivalente incorporadas desde helpers reproducibles:", r"\begin{itemize}"]
    figure_blocks = []
    for payload in payloads:
        if not payload:
            continue
        results = payload.get("results") or payload
        label = results.get("line_label") or results.get("target") or payload.get("tool", "EW")
        order = results.get("order_1based", "pendiente")
        ew_ma = results.get("ew_milliangstrom")
        uncertainty_ma = results.get("uncertainty_milliangstrom")
        if ew_ma is not None and uncertainty_ma is not None:
            lines.append(
                rf"\item {tex_escape(str(label))}, orden {tex_escape(str(order))}: EW = {float(ew_ma):.1f} $\pm$ {float(uncertainty_ma):.1f} m\AA."
            )
        elif ew_ma is not None:
            lines.append(rf"\item {tex_escape(str(label))}, orden {tex_escape(str(order))}: EW = {float(ew_ma):.1f} m\AA.")
        else:
            lines.append(rf"\item {tex_escape(str(label))}: medición pendiente de revisar.")
        notes = payload.get("notes") or []
        if notes:
            lines.append(rf"\item Nota metodológica: {tex_escape(str(notes[0]))}")
        figure_name = copy_artifact_if_exists(payload.get("artifacts", {}).get("plot"), project_dir / "figures")
        if figure_name:
            artifacts.append(str(project_dir / "figures" / figure_name))
            figure_blocks.extend(
                [
                    r"\begin{figure}[h]",
                    r"\centering",
                    rf"\includegraphics[width=0.9\linewidth]{{figures/{tex_escape(figure_name)}}}",
                    rf"\caption{{Medida reproducible de {tex_escape(str(label))}.}}",
                    r"\end{figure}",
                ]
            )
    lines.append(r"\end{itemize}")
    lines.extend(figure_blocks)
    return "\n".join(lines), artifacts


def populate_external_reference_discussion(payload: dict) -> str:
    def fmt_number(value, digits: int = 2) -> str:
        try:
            return f"{float(value):.{digits}f}"
        except (TypeError, ValueError):
            return str(value)

    def fmt_yes_no(value) -> str:
        if value is True:
            return "si"
        if value is False:
            return "no"
        return str(value)

    if not payload:
        return (
            "Los resultados automáticos que entran aquí deben leerse con prudencia: la ruta reproduce bien el trabajo no destructivo, "
            "la trazabilidad y una primera pasada científica, pero no sustituye el criterio manual en la inspección de picos CCF, "
            "en la selección final de órdenes ni en la interpretación física de los espectros substraídos."
        )
    results = payload.get("results", {})
    lines = [
        "La comparación externa se usa como control de plausibilidad, no como sustituto del procedimiento del guion.",
        "",
    ]
    pw = results.get("pw_and", {})
    if pw:
        lines.append("Para PW And:")
        lines.append(r"\begin{itemize}")
        for item in pw.get("comparisons", []):
            units = tex_escape(str(item.get("units", "")))
            units_text = f" {units}" if units else ""
            lines.append(
                rf"\item {tex_escape(item.get('metric', 'comparacion'))}: observado={tex_escape(fmt_number(item.get('observed')))}, referencia={tex_escape(fmt_number(item.get('reference')))}{units_text}, estado=\texttt{{{tex_escape(str(item.get('status')))}}}."
            )
        lines.append(r"\end{itemize}")
    gz = results.get("gz_leo", {})
    if gz:
        lines.append("Para 2REJ1101+223/GZ Leo:")
        lines.append(r"\begin{itemize}")
        expected = gz.get("expected_from_orbit", {})
        if expected:
            lines.append(
                rf"\item Fase orbital estimada={fmt_number(expected.get('phase'), 4)}; RV esperada primaria/secundaria={fmt_number(expected.get('primary_expected_rv_kms'))}/{fmt_number(expected.get('secondary_expected_rv_kms'))} km/s."
            )
        lines.append(rf"\item Sospecha de intercambio de componente o centro CCF inadecuado: \texttt{{{tex_escape(fmt_yes_no(gz.get('component_swap_suspected')))}}}.")
        suggestion = gz.get("ccf_window_suggestion", {})
        if suggestion:
            lines.append(
                rf"\item Para revisar \texttt{{fxcor}}: primera pasada amplia \texttt{{window={suggestion.get('broad_first_pass_window')}}}; después probar centros aproximados \texttt{{wincenter={fmt_number(suggestion.get('expected_primary_wincenter_kms'), 1)}}} y \texttt{{wincenter={fmt_number(suggestion.get('expected_secondary_wincenter_kms'), 1)}}} km/s."
            )
        lines.append(r"\end{itemize}")
    warnings = results.get("warnings", [])
    if warnings:
        lines.append("Avisos automáticos:")
        lines.append(r"\begin{itemize}")
        for item in warnings:
            lines.append(rf"\item \texttt{{{tex_escape(str(item))}}}")
        lines.append(r"\end{itemize}")
    return "\n".join(lines)


def cmd_populate(args):
    configure_runtime("legacy_spectroscopy_report_builder_populate")
    project_dir = Path(args.project_dir).expanduser().resolve()
    if not (project_dir / "main.tex").exists():
        raise SystemExit("El directorio indicado no parece un scaffold de legacy_spectroscopy_report_builder.")

    env_payload = load_json(args.envcheck)
    inventory_payload = load_json(args.inventory_summary)
    fxcor_payloads = [load_json(item) for item in args.fxcor_summary]
    rv_payload = load_json(args.rv_summary)
    istarmod_payload = load_json(args.istarmod_summary)
    li_payloads = [load_json(item) for item in args.li_summary]
    external_reference_payload = load_json(args.external_reference_summary)

    generated_artifacts = []
    write_text(project_dir / "sections" / "02_entorno_trazabilidad.tex", populate_env_section(project_dir, env_payload))
    inventory_text, inventory_artifacts = populate_inventory_section(project_dir, inventory_payload)
    generated_artifacts.extend(inventory_artifacts)
    write_text(project_dir / "sections" / "03_inventario_multispec.tex", inventory_text)
    rv_text, vsini_text, rv_artifacts = populate_rv_sections(project_dir, fxcor_payloads, rv_payload)
    generated_artifacts.extend(rv_artifacts)
    write_text(project_dir / "sections" / "04_velocidad_radial.tex", rv_text)
    write_text(project_dir / "sections" / "05_vsini.tex", vsini_text)
    istarmod_text, ist_artifacts = populate_istarmod_section(project_dir, istarmod_payload)
    generated_artifacts.extend(ist_artifacts)
    write_text(project_dir / "sections" / "06_istarmod.tex", istarmod_text)
    ew_text, ew_artifacts = populate_equivalent_width_section(project_dir, li_payloads)
    generated_artifacts.extend(ew_artifacts)
    write_text(project_dir / "sections" / "07_anchuras_equivalentes.tex", ew_text)

    if env_payload:
        practice_assets = env_payload.get("results", {}).get("detected_practice_assets", {})
        objective_text = (
            "La memoria se centra en una práctica universitaria de espectroscopia legacy que combina PDFs de guion, espectros echelle MULTISPE, correlación cruzada con IRAF/fxcor, una calibración FWHM--$v \\sin i$ e iSTARMOD para sustracción espectral.\n\n"
            f"Material detectado automáticamente: {tex_escape(str(practice_assets.get('fits_count', 0)))} FITS, "
            f"calibración externa \\texttt{{{tex_escape(str(practice_assets.get('calibration_csv', 'pendiente')))}}} e "
            f"iSTARMOD local \\texttt{{{tex_escape(str(practice_assets.get('istarmod_root', 'pendiente')))}}}."
        )
        write_text(project_dir / "sections" / "01_objetivo_materiales.tex", objective_text)

    if rv_payload or istarmod_payload or external_reference_payload:
        write_text(project_dir / "sections" / "08_discusion.tex", populate_external_reference_discussion(external_reference_payload))
    write_text(
        project_dir / "sections" / "09_apendices.tex",
        "Incluye aquí los comandos usados, logs relevantes, decisiones manuales sobre la CCF y cualquier comparación con literatura que no quepa en el cuerpo principal.",
    )

    payload = standard_tool_payload(
        "legacy_spectroscopy_report_builder.populate",
        status="ok",
        notes=["Proyecto de memoria actualizado con las salidas reales disponibles."],
        artifacts={"project_dir": str(project_dir), "generated_artifacts": generated_artifacts},
        results={"populated_sections": [item[0] for item in SECTION_FILES]},
    )
    rendered = json.dumps(payload, indent=2, ensure_ascii=True)
    print(rendered)
    if args.summary_json:
        Path(args.summary_json).write_text(rendered + "\n", encoding="utf-8")
    if args.manifest_json:
        inputs = [Path(item).expanduser().resolve() for item in [args.envcheck, args.inventory_summary, args.rv_summary, args.istarmod_summary, args.external_reference_summary] if item]
        inputs.extend(Path(item).expanduser().resolve() for item in args.fxcor_summary)
        inputs.extend(Path(item).expanduser().resolve() for item in args.li_summary)
        write_manifest(args.manifest_json, inputs=inputs, outputs=[project_dir], parameters={"tool": "legacy_spectroscopy_report_builder.populate"}, command=" ".join(sys.argv), notes=payload["notes"])


def main():
    args = parse_args()
    if args.command == "scaffold":
        try:
            return cmd_scaffold(args)
        except InputValidationError as error:
            return emit_blocked_scaffold(args, error)
    elif args.command == "populate":
        cmd_populate(args)
        return 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
