import SwiftUI

struct LegacyReportPopulateView: View {
  @ObservedObject var store: WorkbenchStore
  let capability: CapabilityEntry

  @State private var projectPath = ""
  @State private var evidenceRoles: [String: LegacyReportEvidenceRole] = [:]
  @State private var evidenceReviews: [String: LegacyReportEvidenceReview] = [:]
  @State private var evidenceErrors: [String: String] = [:]
  @State private var mappingConfirmed = false
  @State private var runError: String?

  private let evidenceService = LegacyReportEvidenceService()

  var body: some View {
    VStack(alignment: .leading, spacing: 14) {
      HStack {
        VStack(alignment: .leading, spacing: 4) {
          Text("Legacy Report Evidence Mapping")
            .font(.headline)
          Text("Choose a scaffold and explicitly assign each summary JSON to the report section it should populate.")
            .font(.callout)
            .foregroundStyle(.secondary)
        }
        Spacer()
        if let validation {
          StatusBadge(status: validation.status.rawValue)
        }
      }

      Picker("Report scaffold", selection: $projectPath) {
        Text("Select").tag("")
        ForEach(directoryCandidates, id: \.self) { path in
          Text(URL(fileURLWithPath: path).lastPathComponent).tag(path)
        }
      }
      .pickerStyle(.menu)

      if evidenceCandidates.isEmpty {
        Text("Attach the scaffold folder and at least one summary JSON generated by a reviewed legacy workflow.")
          .font(.caption)
          .foregroundStyle(.orange)
      } else {
        Grid(alignment: .leading, horizontalSpacing: 14, verticalSpacing: 8) {
          GridRow {
            Text("Evidence file").fontWeight(.semibold)
            Text("Detected provenance").fontWeight(.semibold)
            Text("Report role").fontWeight(.semibold)
          }
          Divider().gridCellColumns(3)
          ForEach(evidenceCandidates, id: \.self) { path in
            GridRow {
              Text(URL(fileURLWithPath: path).lastPathComponent)
                .lineLimit(1)
                .truncationMode(.middle)
              evidenceDescription(path)
              Picker("Role", selection: roleBinding(for: path)) {
                ForEach(LegacyReportEvidenceRole.allCases) { role in
                  Text(role.title).tag(role)
                }
              }
              .labelsHidden()
              .pickerStyle(.menu)
            }
            .font(.caption)
          }
        }
      }

      Toggle(
        "I reviewed the provenance and confirm this evidence-to-section mapping.",
        isOn: $mappingConfirmed
      )
      .toggleStyle(.checkbox)

      validationPanel

      HStack {
        Text("Scientific Workbench will copy the scaffold into the current run before any section is updated. The attached project and JSON evidence remain unchanged.")
          .font(.caption)
          .foregroundStyle(.secondary)
        Spacer()
        Button {
          Task { await runReviewedPopulate() }
        } label: {
          Label("Populate Isolated Report", systemImage: "doc.badge.gearshape")
        }
        .buttonStyle(.borderedProminent)
        .disabled(validation?.canRun != true || store.hasActiveJob)
      }
    }
    .task(id: store.inputPaths) {
      reconcileInputs()
    }
    .onChange(of: projectPath) {
      mappingConfirmed = false
      runError = nil
    }
  }

  private var directoryCandidates: [String] {
    store.inputPaths.filter { path in
      var isDirectory: ObjCBool = false
      return FileManager.default.fileExists(atPath: path, isDirectory: &isDirectory)
        && isDirectory.boolValue
    }
  }

  private var evidenceCandidates: [String] {
    store.inputPaths.filter { path in
      var isDirectory: ObjCBool = false
      return FileManager.default.fileExists(atPath: path, isDirectory: &isDirectory)
        && !isDirectory.boolValue
        && URL(fileURLWithPath: path).pathExtension.lowercased() == "json"
    }
  }

  private var selection: LegacyReportPopulateSelection {
    LegacyReportPopulateSelection(
      projectPath: projectPath,
      assignments: evidenceCandidates.map {
        LegacyReportEvidenceAssignment(
          path: $0,
          role: evidenceRoles[$0] ?? .unused
        )
      },
      mappingConfirmed: mappingConfirmed
    )
  }

  private var validation: LegacyReportPopulateValidation? {
    guard !projectPath.isEmpty else { return nil }
    return evidenceService.validate(
      selection: selection,
      attachedInputPaths: store.inputPaths,
      reviews: evidenceReviews
    )
  }

  @ViewBuilder
  private func evidenceDescription(_ path: String) -> some View {
    if let error = evidenceErrors[path] {
      Label(error, systemImage: "exclamationmark.triangle.fill")
        .foregroundStyle(.red)
    } else if let review = evidenceReviews[path] {
      VStack(alignment: .leading, spacing: 2) {
        Text(review.toolID ?? "No tool identifier")
          .lineLimit(1)
          .truncationMode(.middle)
        if let status = review.status {
          Text(status.uppercased())
            .foregroundStyle(.secondary)
        }
      }
    } else {
      Text("Not inspected")
        .foregroundStyle(.secondary)
    }
  }

  @ViewBuilder
  private var validationPanel: some View {
    if let runError {
      Label(runError, systemImage: "exclamationmark.triangle.fill")
        .font(.caption)
        .foregroundStyle(.red)
    }
    if let validation {
      ForEach(validation.findings, id: \.self) { finding in
        Label(finding, systemImage: "exclamationmark.triangle")
          .font(.caption)
          .foregroundStyle(validation.status == .blocked ? Color.red : Color.orange)
      }
      ForEach(validation.nextActions, id: \.self) { action in
        Label(action, systemImage: "arrow.right")
          .font(.caption)
          .foregroundStyle(.secondary)
      }
    }
  }

  private func roleBinding(for path: String) -> Binding<LegacyReportEvidenceRole> {
    Binding(
      get: { evidenceRoles[path] ?? .unused },
      set: { role in
        evidenceRoles[path] = role
        mappingConfirmed = false
        runError = nil
      }
    )
  }

  private func reconcileInputs() {
    let directories = directoryCandidates
    if !directories.contains(projectPath) {
      projectPath = directories.count == 1 ? directories[0] : ""
    }
    let candidates = Set(evidenceCandidates)
    evidenceRoles = evidenceRoles.filter { candidates.contains($0.key) }
    evidenceReviews = [:]
    evidenceErrors = [:]
    for path in evidenceCandidates {
      evidenceRoles[path] = evidenceRoles[path] ?? .unused
      do {
        evidenceReviews[path] = try evidenceService.inspect(path: path)
      } catch {
        evidenceErrors[path] = error.localizedDescription
      }
    }
    mappingConfirmed = false
    runError = nil
  }

  @MainActor
  private func runReviewedPopulate() async {
    runError = nil
    do {
      let prepared = try evidenceService.prepare(
        selection: selection,
        attachedInputPaths: store.inputPaths,
        reviews: evidenceReviews
      )
      await store.runGuided(
        capability: capability,
        inputPathsOverride: prepared.inputPaths
      ) { runURL in
        prepared.arguments(runURL: runURL)
      }
    } catch {
      runError = error.localizedDescription
    }
  }
}
